services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - '3000:3000'

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      NODE_ENV: development

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - nestjs-app-network

  postgres:
    image: postgres:16-alpine
    container_name: stayflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432',
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-app-network

volumes:
  postgres_data:

networks:
  nestjs-app-network:
    driver: bridge
